library(ggplot2)
ggplot(data=SHEET_1)
ggplot(data=newDATASET,aes(x=newDATASET$S.NO,y=newDATASET$RATING))+geom_point()
ggplot(data=newDATASET,aes(x=newDATASET$S.NO,y=newDATASET$RATING,fill=newDATASET$ALLERGIES))+geom_boxplot()
ggplot(data=newDATASET,aes(x=newDATASET$`PATIENT WEIGHT`,y=newDATASET$RATING,fill=newDATASET$`SURGERY TYPE`))+geom_boxplot()
ggplot(data=newDATASET,aes(x=newDATASET$`PATIENT AGE`,y=newDATASET$RATING,fill=newDATASET$`SURGERY TYPE`))+geom_boxplot()
ggplot(data=newDATASET,aes(x=newDATASET$`PATIENT HEART BEAT`,y=newDATASET$RATING,fill=newDATASET$`SURGERY TYPE`))+geom_boxplot()
ggplot(data=newDATASET,aes(x=newDATASET$`PATIENT BLOOD PRESSURE`,y=newDATASET$RATING,fill=newDATASET$`SURGERY TYPE`))+geom_boxplot()
ggplot(data=newDATASET,aes(x=newDATASET$`PATIENT RESPIRATION RATE`,y=newDATASET$RATING,fill=newDATASET$`SURGERY TYPE`))+geom_boxplot()
ggplot(data=newDATASET,aes(x=newDATASET$`PATIENT WEIGHT`,y=newDATASET$`PATIENT BLOOD PRESSURE`,fill=newDATASET$`SURGERY TYPE`))+geom_boxplot()
ggplot(data=newDATASET,aes(x=newDATASET$S.NO,y=newDATASET$RATING,fill=newDATASET$`SURGERY TYPE`))+geom_boxplot()
ggplot(data=newDATASET,aes(x=newDATASET$`SURGERY LENGTH`,y=newDATASET$RATING))+geom_smooth()
ggplot(data=newDATASET,aes(x=newDATASET$`PATIENT WEIGHT`,y=newDATASET$RATING))+geom_smooth()
ggplot(data=newDATASET,aes(x=newDATASET$`PATIENT RESPIRATION RATE`,y=newDATASET$RATING))+geom_smooth()
ggplot(data=newDATASET,aes(x=newDATASET$`OXYGEN SATURATION`,y=newDATASET$RATING))+geom_smooth()
ggplot(data=newDATASET,aes(x=newDATASET$y=newDATASET$RATING))+geom_smooth()
ggplot(data=newDATASET,aes(x=newDATASET$`PATIENT WEIGHT`,y=newDATASET$`PATIENT AGE`))+geom_smooth()
ggplot(data=newDATASET,aes(x=newDATASET$`PATIENT HEART BEAT`,y=newDATASET$`PATIENT BLOOD PRESSURE`))+geom_smooth()
ggplot(data=newDATASET,aes(x=newDATASET$`PATIENT WEIGHT`,y=newDATASET$HEIGHT))+geom_smooth()



ggplot(data=newDATASET,aes(x=newDATASET$`SURGERY LENGTH`))+geom_freqpoly()
ggplot(data=newDATASET,aes(x=newDATASET$`PATIENT WEIGHT`))+geom_freqpoly()
ggplot(data=newDATASET,aes(x=newDATASET$`PATIENT AGE`))+geom_freqpoly()
ggplot(data=newDATASET,aes(x=newDATASET$`PATIENT HEART BEAT`))+geom_freqpoly()
ggplot(data=newDATASET,aes(x=newDATASET$`PATIENT BLOOD PRESSURE`))+geom_freqpoly()
ggplot(data=newDATASET,aes(x=newDATASET$`PATIENT RESPIRATION RATE`))+geom_freqpoly()
ggplot(data=newDATASET,aes(x=newDATASET$`OXYGEN SATURATION`))+geom_freqpoly()
